name       : libfakekey
version    : '0.3'
release    : 2
source     :
    - http://git.yoctoproject.org/clean/cgit.cgi/libfakekey/snapshot/libfakekey-0.3.tar.bz2 : 4e2fdc9bc20df469d53885c40e104122140131e06d4c184902070ec0b0f2ca9f
license    : GPL-2.0
component  : programming.library
summary    : X virtual keyboard library
description: |
    X virtual keyboard library for converting characters into X server key presses
builddeps  :
    - pkgconfig(xtst)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
